def busca_map_json():
    return {
    "Auditoria Brasil Vexado": {
        "1": "Existe controle de pragas e vetores na unidade? Está atualizado?",
        "2": "O certificado de potabilidade da água e limpeza da caixa de água está dentro do prazo de validade?",
        "3": "O teto / forro encontra-se íntegro e limpo?",
        "4": "O estoque da unidade está com os demais itens em conformidade com o exigido pela Rede e legislações vigentes? Exemplo: Não possui caixa de papelão, não utilizar pano de algodão, não possui objetos em desuso?",
        "5": "A unidade possui todos os insumos necessários para produção do cardápio e esses insumos são das marcas homologadas pela Rede?",
        "6": "O piso encontra-se íntegro (ausência de frestas e rachaduras) e limpo?",
        "7": "As instalações elétricas estão embutidas ou protegidas em tubulações externas e íntegras de tal forma a permitir a higienização dos ambientes?",
        "8": "Os equipamentos, móveis e utensílios são mantidos em adequado estado de conservação, não sendo de madeira?",
        "9": "Da perspectiva de segurança alimentar, equipamentos e utensílios estão PLENAMENTE LIMPOS (Equipamentos e utensílios onde o alimento é manipulado está limpo, sem acúmulo de sujidade, de maneira que não oferecem risco de contaminação aos alimentos) Marque apenas as não conformidades.",
        "10": "Os kits obrigatórios (guardanapos ensacados personalizados, talheres e molhos prontos) estão no padrão da Rede?",
        "11": "As paredes são materiais impermeáveis, laváveis e encontram-se íntegras e limpas?",
        "12": "As planilhas da unidade estão sendo monitoradas e preenchidas diariamente ou sempre que necessário conforme orientações dos consultores?",
        "13": "A unidade possui nota no IFOOD acima de 4,4?",
        "14": "Todos os produtos estão dentro da validade primária (validade do fabricante)?",
        "15": "Unidade possui todas as embalagens obrigatórias: Caixinhas, saco Kraft e Forro de mesa/bandeja?",
        "16": "A unidade possui todas a proteínas necessárias para a produção do cardápio?",
        "17": "Existe lavatório exclusivo para a higiene das mãos na área de manipulação? Estes possuem sabão bactericida neutro e produto anti-séptico, toalhas de papel não reciclado?",
        "18": "Os produtos saneantes utilizados na unidade são regularizados pelo Ministério da Saúde? Estes por sua vez quando abertos, são identificados e guardados em local reservado? Unidade possui produto clorado para higiene dos vegetais?",
        "19": "Valor em branco",
        "20": "Os óleos e gorduras utilizados são aquecidos a temperaturas inferiores a 180ºC, sendo substituídos imediatamente sempre que houver alteração?",
        "21": "Os alimentos preparados, após a cocção, possuem temperatura superior a 60ºC (sessenta graus Celsius) por, no máximo, 6 (seis) horas? Quando resfriados, mantidos à temperatura inferior a 5ºC (cinco graus Celsius)?",
        "22": "Os uniformes estão completos e no padrão da Rede?",
        "23": "Todos os produtos estão corretamente etiquetados e dentro da validade secundária?",
        "24": "EM CASO DE OPOSIÇÃO A ALGUM ITEM SINALIZADO NA AUDITORIA, ENTRAR EM CONTATO PELO E-MAIL AUDITORIA@SUSHILOKO.COM.BR, EM ATÉ 72 HORAS, NO MÁXIMO. AS CONTESTAÇÕES ENVIADAS FORA DO PRAZO OU POR OUTROS MEIOS DE COMUNICAÇÃO NÃO SERÃO ACEITAS.",
        "25": "Os alimentos estão armazenados de forma organizada, em local limpo, separadamente de materiais de limpeza?",
        "26": "As TVs estão passando conteúdo padrão Brasil Vexado?",
        "27": "Todos os itens de programação visual estão presentes (sinalização nos vidros da loja, placas sinalizadoras?",
        "28": "A unidade encontra-se livre de pragas urbanas (Rato, Barata, Moscas, Formigas e outros insetos)?",
        "29": "Os ralos estão limpos? São sifonados e as grelhas possuem dispositivo que permitam seu fechamento?",
        "30": "O coletor de gordura está limpo e cheio de água (CHARBROIL) ?",
        "31": "Toda documentação dos colaboradores está disponível e atualizada? Atendente, Caixa, Gerente, e Encarregado: Exame Clínico. Setor de produção: Fezes (EPF), Urina (EAS), Hemograma Completo e exame micológico de unhas, porém, caso esses colaboradores não o apresentam fica vetada a manipulação de alimentos?",
        "32": "As janelas possuem telas milimétricas removíveis, íntegras e limpas?",
        "33": "A organização das geladeiras e freezers está sendo realizadas de forma adequada?",
        "34": "Estão usando bandejas, utensílios e louças em perfeito estado de conservação, higiene , tanto no atendimento quanto na área de produção?",
        "35": "A chapa/Grelha está limpa e funcionando com temperatura correta 320° C ?",
        "36": "A unidade possui nota no IFOOD acima de 4,2?",
        "37": "A unidade possui todos os equipamentos exigidos pela franqueadora em quantidade adequada e funcionando perfeitamente?",
        "38": "Na parte hidráulica, elétrica, estão funcionando de forma correta ou em perfeito estado de conservação?",
        "39": "Os Molhos padronizados exigidos pela Franqueadora estão sendo utilizados em loja?"
    },
    "Auditoria Hum Burguer": {
        "1": "Na parte hidráulica, elétrica, manutenção em geral (torneiras, vaso sanitário, tomada, etc) estão funcionando de forma correta ou em perfeito estado de conservação?",
        "2": "Os materiais publicitários obrigatórios encontram-se presentes na loja (Adesivos,banner, display, material de campanha vigente, cartaz explicativo da manobra de Heimlich, PROCON) e estão em locais adequados? (Material de atração externa deve ficar fora da loja, enquanto de conversão deve estar dentro da loja).",
        "3": "A unidade possui nota no IFOOD acima de 4,4?",
        "4": "As paredes são materiais impermeáveis, laváveis e encontram-se íntegras e limpas?",
        "5": "A iluminação está adequada, com protetores anti explosão e queda?",
        "6": "O teto / forro encontra-se íntegro e limpo?",
        "7": "O piso encontra-se íntegro (ausência de frestas e rachaduras) e limpo?",
        "8": "A unidade possui todos os equipamentos exigidos pela franqueadora em quantidade adequada e funcionando perfeitamente?",
        "9": "Da perspectiva de segurança alimentar, equipamentos e utensílios estão PLENAMENTE LIMPOS (equipamentos e utensílios onde o alimento é manipulado está limpo, sem acúmulo de sujidade, de maneira que não ofereçam risco de contaminação aos alimentos). Marque apenas as não conformidades.",
        "10": "Unidade possui todas as embalagens obrigatórias: (Papel calcinha, caixa de batata frita, Saco kraft, Papel bandeja metálica para servir disponíveis?",
        "11": "Os equipamentos e móveis são mantidos em adequado estado de conservação e são resistentes à corrosão repetidas operações de limpeza e desinfecção, não sendo de madeira?",
        "12": "Todos os produtos estão dentro da validade primária (validade do fabricante)?",
        "13": "A unidade possui todos os pães necessários para produção do cardápio e esses insumos são das marcas homologada e estão marcados com a logo da empresa? Encontram se armazenados conforme orientações da rede?",
        "14": "Os produtos abaixo encontram-se no padrão da Rede? Armazenamento adequado, Gramatura, tamanho, sabor e forma de preparo?",
        "15": "As bebidas estão com a temperatura adequada? Há limão e/ou laranja cortados? Há gelo na loja?",
        "16": "A Coifa está limpa, ligada e em pleno funcionamento?",
        "17": "A temperatura da área de atendimento está adequada? Caso tenha ar condicionado, verificar as condições do equipamento.",
        "18": "Todos os produtos estão corretamente etiquetados e dentro da validade secundária?",
        "19": "O estoque da unidade está com os demais itens em conformidade com o exigido pela Rede e legislações vigentes? Exemplo: não possuir caixa de papelão na unidade, não utilizar pano de algodão, não possui objetos em desuso?",
        "20": "A organização das geladeiras e freezers está sendo realizadas de forma adequada? Ordem de produtos prontos (prateleira superior), semi-prontos (prateleira intermediário) e crus (prateleira inferior) estão sendo seguidas?",
        "21": "As temperaturas de equipamentos estão dentro do estipulado pela legislação vigente, exceto freezer de bebidas? Equipamentos refrigeradores de 0,0 ºC até 4,9ºC ; equipamentos congeladores de -12ºC até -22ºC e banho Maria acima de 60ºC).",
        "22": "EM CASO DE OPOSIÇÃO A ALGUM ITEM SINALIZADO NA AUDITORIA, ENTRAR EM CONTATO PELO E-MAIL AUDITA@LAGOFRANQUIAS.COM, EM ATÉ 72 HORAS, NO MÁXIMO. AS CONTESTAÇÕES ENVIADAS FORA DO PRAZO OU POR OUTROS MEIOS DE COMUNICAÇÃO NÃO SERÃO ACEITAS.",
        "23": "A unidade possui todos os pães necessários para produção do cardápio e esses insumos são das marcas homologada? Encontram se armazenados conforme orientações da rede?",
        "24": "Os produtos saneantes utilizados na unidade são regularizados pelo Ministério da Saúde? Estes por sua vez quando abertos, são identificados e guardados em local reservado para essa finalidade?",
        "25": "Os cardápios estão em quantidade suficiente e em bom estado de conservação?",
        "26": "O restaurante está bem iluminado, sem lâmpadas queimadas e colorações diferentes?",
        "27": "Existe controle de pragas e vetores na unidade? Está atualizado?",
        "28": "Todos os produtos altamente intoxicavéis estão adequados para o consumo (Características sensoriais como cor, sabor, odor e textura)?",
        "29": "Os ralos estão limpos? São sifonados e as grelhas possuem dispositivo que permitam seu fechamento?",
        "30": "Existe lavatório exclusivo para a higiene das mãos na área de manipulação? Estes possuem sabão bactericida neutro e produto anti-séptico, toalhas de papel não reciclado ou outro sistema higiênico e seguro de secagem das mãos e coletor de papel, acionado sem contato manual?",
        "31": "O sistema de ventilação garante o conforto térmico (entre 23ºC e 26ºC nas áreas de manipulação)?",
        "32": "As portas estão integras limpas, sem frestas, ajustadas ao batente e possuem tela milimétrica caso haja contato com o exterior?",
        "33": "As janelas possuem telas milimétricas removíveis, íntegras e limpas?",
        "34": "Estão usando bandejas, utensílios e louças em perfeito estado de conservação e higiene, tanto no atendimento quanto na área de produção?",
        "35": "As áreas ao redor encontram-se livres de focos de contaminação (acúmulo de lixo, restos de obra, objetos que proporcionem a multiplicação de pragas e vetores?).",
        "36": "A unidade possui todos os insumos necessários para produção do cardápio e esses insumos são das marcas homologadas pela Rede?",
        "37": "Os molhos padronizados exigidos pela franqueadora estão sendo utilizados em loja? Molho BARBECUE, Molho HONEY, Molho RANCH, Maionese GRILL, Ketchup, Mostarda e Maionese Heinz.",
        "38": "Os pratos executivos estão em temperatura adequada? Bem montados, enfeitados, sendo servidos com molhos corretos e em louças/embalagens apropriadas?",
        "39": "Os kits obrigatórios ( guardanapos ensacados personalizados, sachê de ketchup, mostarda e maionese Heinz) para o Delivery ou para Viagem estão sendo preparados, montados e enviados dentro do padrão da Rede?",
        "40": "As planilhas da unidade estão sendo monitoradas e preenchidas diariamente ou sempre que necessário conforme orientações dos consultores?",
        "41": "O Coletor de gordura está limpo e cheio de água (charbroil)?",
        "42": "Os alimentos estão armazenados de forma organizada, em local limpo, separadamente de materiais de limpeza e descartáveis, colocados sobre paletes/estrados ou prateleiras e com espaçamento mínimo necessário para garantir adequada ventilação e limpeza do local?",
        "43": "Os uniformes estão completos e no padrão da Rede? (Calça, camisa, touca, sapato fechado e avental para equipe de produção).",
        "44": "A rotatividade dos produtos (PVPS - primeiro que vence, primeiro que sai), está sendo realizado corretamente em todos os produtos? Estoque seco, refrigerado, congelado e freezer de bebidas?",
        "45": "A limpeza e organização da área de atendimento em geral (área visível ao cliente) estão no padrão?",
        "46": "Os insumos necessários para as preparações estão prontos e disponíveis no balcão refrigerado próximo á grelha?",
        "47": "Os alimentos preparados, após a cocção, possuem temperatura superior a 60ºC (sessenta graus Celsius) por, no máximo, 6 (seis) horas? Quando resfriados, mantidos à temperatura inferior a 5ºC (cinco graus Celsius)?",
        "48": "Os óleos e gorduras utilizados são aquecidos a temperaturas inferiores a 180ºC, sendo substituídos imediatamente sempre que houver alteração evidente das características físico-químicas ou sensoriais, tais como aroma e sabor, e formação intensa de espuma e fumaça?",
        "49": "Toda documentação dos colaboradores está disponível e atualizada? Atendente, caixa, gerente e encarregado: exame clínico. Setor de produção: Fezes (EPF), Urina (EAS), hemograma completo e exame micológico das unhas. (É opcional que atendentes, caixa, encarregado e gerente faça o exame micológico de unhas, porém, caso esses colaboradores não o apresentem fica vetada a manipulação de alimentos.)",
        "50": "A unidade possui certificado de limpeza do exaustor, dentro do prazo de validade de seis meses?",
        "51": "A Chapa/Grelha está limpa e funcionando com temperatura correta 320º C?",
        "52": "Os materiais publicitários obrigatórios encontram-se presentes na loja (Adesivos,banner, display, material de campanha vigente, SAS, PROCON) e estão em locais adequados? (Material de atração externa deve ficar fora da loja, enquanto de conversão deve estar dentro da loja).",
        "53": "A unidade possui nota no IFOOD acima de 4,2?",
        "54": "A unidade possui Manual de Boas Práticas de Fabricação (BPF)? Está atualizado?",
        "55": "Os banheiros estão limpos e sem odor, com papel higiênico, sabonete neutro, papel toalha e lixeira? Estes se encontram em perfeito estado de conservação?",
        "56": "Os produtos abaixo encontram-se no padrão da Rede? Gramatura, tamanho, sabor e forma de preparo?",
        "57": "O descongelamento de proteínas está sendo feito de forma adequada e de acordo com o prazo de validade para descongelamento? (Permitido apenas dentro de refrigerador e separado conforme gêneros alimentícios)",
        "58": "O local destinado a higienização de equipamentos de limpeza encontra-se limpo e organizado (rodos, pás de lixo, carrinho MOP, esfregões, baldes, luvas de limpeza)?",
        "59": "O sistema de ventilação garante o conforto térmico (entre 23ºC e 26ºC nas áreas de manipulação)? A renovação do ar e a manutenção do ambiente livre de fungos, gases, fumaça, gordura e condensação de vapores, dentre outros?",
        "60": "A CHAPA/GRELHA está limpa e funcionando com temperatura correta 320 ºC?",
        "61": "O certificado de potabilidade da água e limpeza da caixa de água está dentro do prazo de validade?",
        "62": "A unidade possui Programa de Controle Medico de Saúde Ocupacional (PCMSO) e Programa de Prevenção de Risco de Acidentes (PPRA) em dias? Caso não tenha, procure um serviço especializado em Engenharia de Segurança e Medicina do Trabalho (SMT).",
        "63": "Freezer 1",
        "64": "Balcão refrigerado embaixo da grelha",
        "65": "Freezer 2",
        "66": "Geladeira 3",
        "67": "Embalagens de sanduíche ( papel calcinha), caixa de batata frita, papel bandeja metálica para servir disponíveis?",
        "68": "Geladeira 1",
        "69": "Geladeira 2",
        "70": "A unidade encontra-se livre de pragas urbanas (ratos, baratas, moscas, formigas e outros insetos) ?",
        "71": "As bebidas Pink Lemonade e Chá Mate de Limão estão no padrão da Rede?",
        "72": "Banho Maria",
        "73": "Os equipamentos, móveis e utensílios são mantidos em adequado estado de conservação e são resistentes à corrosão repetidas operações de limpeza e desinfecção, não sendo de madeira?",
        "74": "Balcão refrigerado",
        "75": "Os insumos necessários para as preparações estão prontos e disponíveis no balcão refrigerador próximo á grelha?",
        "76": "Os manipuladores têm asseio pessoal, apresentam-se com uniformes conservados e limpos diariamente e usados exclusivamente nas dependências internas do estabelecimento?",
        "77": "Os kits obrigatórios ( guardanapos ensacados personalizados, molhos prontos e embalagens) para o Delivery ou para Viagem estão sendo preparados, montados e enviados dentro do padrão da Rede?",
        "78": "Os molhos padronizados exigidos pela franqueadora estão sendo utilizados em loja? Molho BARBECUE, molho HONEY, molho RANCH e maionese GRILL",
        "79": "Os pedidos estão saindo no tempo estimado? (15 minutos no máximo).",
        "80": "As bebidas Pink Lemonade, Chá Mate de Limão e Àgua saborizada estão no padrão da Rede?",
        "81": "Os materiais publicitários obrigatórios encontram-se presentes na loja (banner, display, material de campanha vigente, SAS, PROCON) e estão em locais adequados? (Material de atração externa deve ficar fora da loja, enquanto de conversão deve estar dentro da loja)."
    },
    "Auditoria Sushiloko": {
        "1": "AMOSTRA 5 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "2": "AMOSTRA 4 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "3": "AMOSTRA 3 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "4": "AMOSTRA 2 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "5": "AMOSTRA 1 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "6": "A unidade possui nota no IFOOD acima de 4,4?",
        "7": "Os produtos saneantes utilizados na unidade são regularizados pelo Ministério da Saúde? Estes por sua vez quando abertos, são identificados e guardados em local reservado para essa finalidade?",
        "8": "O sistema de ventilação garante o conforto térmico (entre 23ºC e 26ºC nas áreas de manipulação)?",
        "9": "O piso encontra-se íntegro (ausência de frestas e rachaduras) e limpo?",
        "10": "Da perspectiva de segurança alimentar, equipamentos e utensílios estão PLENAMENTE LIMPOS (equipamentos e utensílios onde o alimento é manipulado está limpo, sem acúmulo de sujidade, de maneira que não ofereçam risco de contaminação aos alimentos). Marque apenas as não conformidades.",
        "11": "Todos os produtos estão corretamente etiquetados e dentro da validade secundária?",
        "12": "A unidade possui todos os equipamentos exigidos pela franqueadora em quantidade adequada e funcionando perfeitamente?",
        "13": "Os alimentos estão armazenados de forma organizada, em local limpo, separadamente de materiais de limpeza e descartáveis, colocados sobre paletes/estrados ou prateleiras e com espaçamento mínimo necessário para garantir adequada ventilação e limpeza do local?",
        "14": "O certificado de potabilidade da água está dentro do prazo de validade?",
        "15": "A unidade possui todos os insumos necessários para produção do cardápio e esses insumos são das marcas homologadas pela Rede?",
        "16": "Os cardápios estão em quantidade suficiente e em bom estado de conservação?",
        "17": "Na parte hidráulica, elétrica, manutenção em geral (torneiras, vaso sanitário, tomada, etc) estão funcionando de forma correta ou em perfeito estado de conservação?",
        "18": "Todos os produtos estão dentro da validade primária (validade do fabricante)?",
        "19": "Os ralos estão limpos? São sifonados e as grelhas possuem dispositivo que permitam seu fechamento?",
        "20": "As paredes são materiais impermeáveis, laváveis e encontram-se íntegras e limpas?",
        "21": "Os produtos abaixo encontram-se no padrão da Rede? Gramatura, tamanho, sabor e forma de preparo?",
        "22": "Os equipamentos e móveis são mantidos em adequado estado de conservação e são resistentes à corrosão repetidas operações de limpeza e desinfecção, não sendo de madeira?",
        "23": "O teto / forro encontra-se íntegro e limpo?",
        "24": "O certificado de higienização do reservatório de água está dentro do prazo de validade?",
        "25": "A temperatura da área de atendimento está adequada? Caso tenha ar condicionado, verificar as condições do equipamento.",
        "26": "TODOS os vegetais para yakissoba estão porcionados em quantidade suficiente, com gramatura correta e em boa aparência, mesmo estando apropriados para consumo?",
        "27": "As portas estão integras limpas, sem frestas, ajustadas ao batente e possuem tela milimétrica caso haja contato com o exterior?",
        "28": "Existe lavatório exclusivo para a higiene das mãos na área de manipulação? Estes possuem sabão bactericida neutro e produto anti-séptico, toalhas de papel não reciclado ou outro sistema higiênico e seguro de secagem das mãos e coletor de papel, acionado sem contato manual?",
        "29": "O descongelamento de proteínas está sendo feito de forma adequada e de acordo com o prazo de validade para descongelamento? (Permitido apenas dentro de refrigerador e separado conforme gêneros alimentícios)",
        "30": "As planilhas da unidade estão sendo monitoradas e preenchidas diariamente ou sempre que necessário conforme orientações dos consultores?",
        "31": "Estão usando bandejas, utensílios e louças em perfeito estado de conservação, higiene , tanto no atendimento quanto na área de produção?",
        "32": "As temperaturas de equipamentos estão dentro do estipulado pela legislação vigente, exceto freezer de bebidas? Equipamentos refrigeradores de 0,0 ºC até 4,9ºC ; equipamentos congeladores de -12ºC até -22ºC e banho Maria acima de 60ºC).",
        "33": "A unidade possui Manual de Boas Práticas de Fabricação (BPF)? Está atualizado?",
        "34": "O certificado de potabilidade da água e limpeza da caixa de água está dentro do prazo de validade?",
        "35": "Todas as mesas possuem shoyo, chamador de garçom e display de mesa e/ou estes são colocados logo ao receber o cliente na unidade, estão funcionando adequadamente?",
        "36": "As planilhas de suporte oferecidas pela Rede estão sendo realizados conforme o recomendado? Marque apenas as opções não conforme.",
        "37": "A unidade possui todas as Proteínas necessárias para a produção do cardápio? As postas e cortes estão no expositor (salmão, peixe branco, kani, camarão, cortes para temaki, super hot, supremo, nigui e jyo)?",
        "38": "Os banheiros estão limpos e sem odor, com papel higiênico, sabonete neutro, papel toalha e lixeira? Estes se encontram em perfeito estado de conservação?",
        "39": "A organização das geladeiras e freezers está sendo realizadas de forma adequada? Ordem de produtos prontos (prateleira superior), semi-prontos (prateleira intermediário) e crus (prateleira inferior) estão sendo seguidas? Obs: Produto cru não pode estar junto com produto cozido ou alimentos diferentes misturados em mesmo recipiente.",
        "40": "As mesas, cadeiras, escadas, vidros em geral estão em bom estado de conservação?",
        "41": "A área do caixa encontra-se devidamente organizada e com todos os materiais e equipamentos necessários: computador, impressora fiscal, troco, bobina reserva?",
        "42": "Todos os itens de programação visual estão presentes (Letreiro, papel de parede, sinalização nos vidros da loja, capacho, placas sinalizadoras (banheiros, extintor, quadro de energia, Saída da cozinha/salão)?",
        "43": "Os materiais publicitários obrigatórios encontram-se presentes na loja (banner, display, material de campanha vigente, SAS, PROCON) e estão em locais adequados? (Material de atração externa deve ficar fora da loja, enquanto de conversão deve estar dentro da loja).",
        "44": "A limpeza e organização da área de atendimento em geral (área visível ao cliente) estão no padrão?",
        "45": "Existe controle de pragas e vetores na unidade? Está atualizado?",
        "46": "As janelas possuem telas milimétricas removíveis, íntegras e limpas?",
        "47": "Os uniformes estão completos e no padrão da Rede? (Calça, camisa, touca, sapato fechado, crachá para atendimento e gerência e avental para equipe de produção)",
        "48": "Unidade possui todas as embalagens obrigatórias: Caixinhas, saco Kraft, Cinta para Temaki e Forro de mesa/bandeja?",
        "49": "Os kits obrigatórios (Hashis com e sem liguinhas, guardanapos ensacados personalizados, shoyuzará descartável e molhos shoyu e teriyaki) para o Delivery ou para Viagem estão sendo preparados, montados e enviados dentro do padrão da Rede?",
        "50": "O estoque da unidade está com os demais itens em conformidade com o exigido pela Rede e legislações vigentes? Exemplo: não possuir caixa de papelão na unidade, não utilizar pano de algodão, não possui objetos em desuso?",
        "51": "As áreas ao redor encontram-se livres de focos de contaminação (acúmulo de lixo, restos de obra, objetos que proporcionem a multiplicação de pragas e vetores?)",
        "52": "O arroz está padrão (consistência e sabor)?",
        "53": "As TVs estão passando conteúdo padrão Sushiloko?",
        "54": "A unidade encontra-se livre de pragas urbanas (ratos, baratas, moscas, formigas e outros insetos) ?",
        "55": "Os pedidos estão saindo no tempo estimado? (50 minutos no máximo).",
        "56": "As bebidas estão com a temperatura adequada? Há limão e/ou laranja cortados? Há gelo na loja?",
        "57": "Os molhos padronizados exigidos pela franqueadora estão sendo utilizados em loja? (Molho Teriaki, Oriental e Calda Sushiloko).",
        "58": "A unidade possui nota no IFOOD acima de 4,2?",
        "59": "Toda documentação dos colaboradores está disponível e atualizada? Atendente, caixa, gerente e encarregado: exame clínico. Setor de produção: Fezes (EPF), Urina (EAS), hemograma completo e exame micológico das unhas. (É opcional que atendentes, caixa, encarregado e gerente faça o exame micológico de unhas, porém, caso esses colaboradores não o apresentem fica vetada a manipulação de alimentos.)",
        "60": "Os manipuladores têm asseio pessoal, apresentam-se com uniformes conservados e limpos diariamente e usados exclusivamente nas dependências internas do estabelecimento?",
        "61": "A iluminação está adequada, com protetores anti explosão e queda?",
        "62": "Todos os produtos altamente intoxicavéis estão adequados para o consumo (Características sensoriais como cor, sabor, odor e textura)?",
        "63": "EM CASO DE OPOSIÇÃO A ALGUM ITEM SINALIZADO NA AUDITORIA, ENTRAR EM CONTATO PELO E-MAIL AUDITORIA@SUSHILOKO.COM.BR, EM ATÉ 72 HORAS, NO MÁXIMO. AS CONTESTAÇÕES ENVIADAS FORA DO PRAZO OU POR OUTROS MEIOS DE COMUNICAÇÃO NÃO SERÃO ACEITAS.",
        "64": "Há sempre um atendente disponível e atento ao chamado dos clientes?",
        "65": "Os óleos e gorduras utilizados são aquecidos a temperaturas inferiores a 180ºC, sendo substituídos imediatamente sempre que houver alteração evidente das características físico-químicas ou sensoriais, tais como aroma e sabor, e formação intensa de espuma e fumaça?",
        "66": "A unidade está utilizando tipos de tábuas e facas diferentes para corte de acordo com cores e gêneros alimentícios, minimizando assim o risco de contaminação cruzada dos alimentos?",
        "67": "O local destinado a higienização de equipamentos de limpeza encontra-se limpo e organizado (rodos, pás de lixo, carrinho MOP, esfregões, baldes, luvas de limpeza)?",
        "68": "A unidade possui Programa de Controle Medico de Saúde Ocupacional (PCMSO) e Programa de Prevenção de Risco de Acidentes (PPRA) em dias? Caso não tenha, procure um serviço especializado em Engenharia de Segurança e Medicina do Trabalho (SMT).",
        "69": "Os kits obrigatórios (Hashis com e sem liguinhas, guardanapos ensacados personalizados, shoyuzará e molhos prontos) para o Delivery ou para Viagem estão sendo preparados, montados e enviados dentro do padrão da Rede?",
        "70": "Todos os itens de programação visual estão presentes (papel de parede, sinalização nos vidros da loja, capacho, placas sinalizadoras (banheiros, extintor, quadro de energia, Saída da cozinha/salão)?",
        "71": "Estão disponíveis (impressos) o alvará de funcionamento e o termo de inspeção sanitária?",
        "72": "A equipe de atendimento executa os 10 passos do atendimento corretamente?",
        "73": "A rotatividade dos produtos (PVPS - primeiro que vence, primeiro que sai), está sendo realizado corretamente em todos os produtos? Estoque seco, refrigerado, congelado e freezer de bebidas?"
    },
    "Auditoria V 2.0": {
        "1": "As TVs estão passando conteúdo padrão Sushiloko?",
        "2": "Fachadas, Menuboard não possuem nenhuma lâmpada queimada? Os displays de mesa encontram limpos e expostos da forma correta?",
        "3": "Freezer 1",
        "4": "Freezer 2",
        "5": "Freezer 3",
        "6": "Geladeira 1",
        "7": "Geladeira 2",
        "8": "Balcão refrigerado",
        "9": "Todos os produtos estão corretamente etiquetados e dentro da validade secundária?",
        "10": "Da perspectiva de segurança alimentar, equipamentos e utensílios estão PLENAMENTE LIMPOS (equipamentos e utensílios onde o alimento é manipulado está limpo, sem acúmulo de sujidade, de maneira que não ofereçam risco de contaminação aos alimentos). Marque apenas as não conformidades.",
        "11": "Todos os itens de programação visual estão presentes (papel de parede, sinalização nos vidros da loja, capacho, placas sinalizadoras (banheiros, extintor, quadro de energia, Saída da cozinha/salão)?",
        "12": "Vitrine/Expositor de peixes",
        "13": "AMOSTRA 1 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "14": "AMOSTRA 2 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "15": "AMOSTRA 3 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "16": "AMOSTRA 4 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "17": "Os equipamentos, móveis e utensílios são mantidos em adequado estado de conservação e são resistentes à corrosão repetidas operações de limpeza e desinfecção, não sendo de madeira?",
        "18": "Estão usando bandejas, utensílios e louças em perfeito estado de conservação e higiene, tanto no atendimento quanto na área de produção?",
        "19": "A temperatura da área de atendimento está adequada? Caso tenha ar condicionado, verificar as condições do equipamento.",
        "20": "O piso encontra-se íntegro (ausência de frestas e rachaduras) e limpo?",
        "21": "A área do caixa encontra-se devidamente organizada e com todos os materiais e equipamentos necessários: computador, impressora fiscal, troco, bobina reserva?",
        "22": "O estoque da unidade está com os demais itens em conformidade com o exigido pela Rede e legislações vigentes? Exemplo: não possuir caixa de papelão na unidade, não utilizar pano de algodão, não possui objetos em desuso?",
        "23": "AMOSTRA 5 - O item escolhidos para pesar / medir está conforme gramatura e receituário da Rede? (Livre escolha do auditor).",
        "24": "A unidade possui Programa de Controle Medico de Saúde Ocupacional (PCMSO) e Programa de Prevenção de Risco de Acidentes (PPRA) em dias? Caso não tenha, procure um serviço especializado em Engenharia de Segurança e Medicina do Trabalho (SMT).",
        "25": "A iluminação está adequada, com protetores anti explosão e queda?",
        "26": "Os materiais publicitários obrigatórios encontram-se presentes na loja (banner, display, material de campanha vigente, SAS, PROCON) e estão em locais adequados? (Material de atração externa deve ficar fora da loja, enquanto de conversão deve estar dentro da loja).",
        "27": "As planilhas da unidade estão sendo monitoradas e preenchidas diariamente ou sempre que necessário conforme orientações dos consultores?",
        "28": "As paredes são materiais impermeáveis, laváveis e encontram-se íntegras e limpas?",
        "29": "O teto / forro encontra-se íntegro e limpo?",
        "30": "Na parte hidráulica, elétrica, manutenção em geral (torneiras, vaso sanitário, tomada, etc) estão funcionando de forma correta ou em perfeito estado de conservação?",
        "31": "Existe lavatório exclusivo para a higiene das mãos na área de manipulação? Estes possuem sabão bactericida neutro e produto anti-séptico, toalhas de papel não reciclado ou outro sistema higiênico e seguro de secagem das mãos e coletor de papel, acionado sem contato manual?",
        "32": "Os produtos abaixo encontram-se no padrão da Rede? Gramatura, tamanho, sabor e forma de preparo?",
        "33": "A unidade possui todos os insumos necessários para produção do cardápio e esses insumos são das marcas homologadas pela Rede?",
        "34": "O arroz está padrão (consistência e sabor)?",
        "35": "A organização das geladeiras e freezers está sendo realizadas de forma adequada? Ordem de produtos prontos (prateleira superior), semi-prontos (prateleira intermediário) e crus (prateleira inferior) estão sendo seguidas? Obs: Produto cru não pode estar junto com produto cozido ou alimentos diferentes misturados em mesmo recipiente.",
        "36": "Todas as postas e cortes estão no expositor (salmão, peixe branco, kani, camarão, Atum (lojas que trabalham com o produto) cortes para temaki, corte para hot, super hot, supremo, nigui e jyo)?",
        "37": "As portas estão integras limpas, sem frestas, ajustadas ao batente e possuem tela milimétrica caso haja contato com o exterior?",
        "38": "Toda documentação dos colaboradores está disponível e atualizada? Atendente, caixa, gerente e encarregado: exame clínico. Setor de produção: Fezes (EPF), Urina (EAS), hemograma completo e exame micológico das unhas. (É opcional que atendentes, caixa, encarregado e gerente faça o exame micológico de unhas, porém, caso esses colaboradores não o apresentem fica vetada a manipulação de alimentos.)",
        "39": "As janelas possuem telas milimétricas removíveis, íntegras e limpas?",
        "40": "As áreas ao redor encontram-se livres de focos de contaminação (acúmulo de lixo, restos de obra, objetos que proporcionem a multiplicação de pragas e vetores?).",
        "41": "Os kits obrigatórios (Hashis com e sem liguinhas, guardanapos ensacados personalizados, shoyuzará e molhos prontos) para o Delivery ou para Viagem estão sendo preparados, montados e enviados dentro do padrão da Rede?",
        "42": "Todos os produtos altamente intoxicavéis estão adequados para o consumo (Características sensoriais como cor, sabor, odor e textura)?",
        "43": "Os pedidos estão saindo no tempo estimado? (15 minutos no máximo).",
        "44": "O restaurante está bem iluminado, sem lâmpadas queimadas e colorações diferentes?",
        "45": "Todas as mesas possuem shoyo, chamador de garçom e display de mesa e/ou estes são colocados logo ao receber o cliente na unidade, estão funcionando adequadamente?",
        "46": "O certificado de potabilidade da água e limpeza da caixa de água está dentro do prazo de validade?",
        "47": "Todos os produtos estão dentro da validade primária (validade do fabricante)?",
        "48": "As mesas, cadeiras, escadas, vidros em geral estão em bom estado de conservação?",
        "49": "TODOS os vegetais para yakissoba estão porcionados em quantidade suficiente, com gramatura correta e em boa aparência, mesmo estando apropriados para consumo?",
        "50": "Os cardápios estão em quantidade suficiente e em bom estado de conservação?",
        "51": "A unidade possui todos os equipamentos exigidos pela franqueadora em quantidade adequada e funcionando perfeitamente?",
        "52": "As planilhas de suporte oferecidas pela Rede estão sendo realizados conforme o recomendado? Marque apenas as opções não conforme.",
        "53": "Os ralos estão limpos? São sifonados e as grelhas possuem dispositivo que permitam seu fechamento?",
        "54": "A unidade possui Manual de Boas Práticas de Fabricação (BPF)? Está atualizado?",
        "55": "Os pratos estão apresentáveis? Bem montados, enfeitados, sendo servidos com molhos corretos e em louças/embalagens apropriadas?",
        "56": "Os alimentos estão armazenados de forma organizada, em local limpo, separadamente de materiais de limpeza e descartáveis, colocados sobre paletes/estrados ou prateleiras e com espaçamento mínimo necessário para garantir adequada ventilação e limpeza do local?",
        "57": "A limpeza e organização da área de atendimento em geral (área visível ao cliente) estão no padrão?",
        "58": "Os uniformes estão completos e no padrão da Rede? (Calça, camisa, touca, sapato fechado, crachá para atendimento e gerência e avental para equipe de produção)",
        "59": "O descongelamento de proteínas está sendo feito de forma adequada e de acordo com o prazo de validade para descongelamento? (Permitido apenas dentro de refrigerador e separado conforme gêneros alimentícios)",
        "60": "Os óleos e gorduras utilizados são aquecidos a temperaturas inferiores a 180ºC, sendo substituídos imediatamente sempre que houver alteração evidente das características físico-químicas ou sensoriais, tais como aroma e sabor, e formação intensa de espuma e fumaça?",
        "61": "O kit endomarketing, cartaz de orientação sobre lavagem e anti-sepsia das mãos, tabela de validade, tabelas de gramaturas, colinhas e kit atendimento estão presentes e colados em locais adequados?",
        "62": "Em caso de oposição a algum item sinalizado na auditoria, entrar em contato pelo e-mail auditoria@sushiloko.com.br, em até 72 horas, no máximo. As contestações enviadas fora do prazo ou por outros meios de comunicação não serão aceitas.",
        "63": "Os manipuladores não praticam atos como fumar, falar desnecessariamente, cantar, assobiar, espirrar, cuspir, tossir, comer, manipular dinheiro ou praticar outros atos que possam contaminar o alimento, durante o desempenho das atividades?",
        "64": "O baú da moto está limpo e organizado? Há kits extras?(Hashis com e sem liguinhas, guardanapos ensacados personalizados, shoyuzará e molhos prontos).",
        "65": "Os molhos padronizados exigidos pela franqueadora estão sendo utilizados em loja? (Molho Teriaki, Oriental e Calda Sushiloko).",
        "66": "Existe controle de pragas e vetores na unidade? Está atualizado?",
        "67": "A unidade encontra-se livre de pragas urbanas (ratos, baratas, moscas, formigas e outros insetos) ?",
        "68": "A equipe de atendimento executa os 10 passos do atendimento corretamente?",
        "69": "A unidade utiliza fritadeira e vasilha devidamente identificada e exclusiva para o preparo do camarão?",
        "70": "Os produtos saneantes utilizados na unidade são regularizados pelo Ministério da Saúde? Estes por sua vez quando abertos, são identificados e guardados em local reservado para essa finalidade?",
        "71": "As bebidas estão com a temperatura adequada? Há limão e/ou laranja cortados? Há gelo na loja?",
        "72": "A rotatividade dos produtos (PVPS - primeiro que vence, primeiro que sai), está sendo realizado corretamente em todos os produtos? Estoque seco, refrigerado, congelado e freezer de bebidas?",
        "73": "O sistema de ventilação garante o conforto térmico (entre 23ºC e 26ºC nas áreas de manipulação)? A renovação do ar e a manutenção do ambiente livre de fungos, gases, fumaça, gordura e condensação de vapores, dentre outros?",
        "74": "Os kits obrigatários (Hashis com e sem liguinhas, guardanapos ensacados personalizados, shoyuzará e molhos prontos) para o Delivery ou para Viagem estão sendo preparados, montados e enviados dentro do padrão da Rede?",
        "75": "Os molhos padronizados exigidos pela franqueadora estão sendo utilizados em loja? Marque apenas opções não conforme."
    },
    "Visita Técnica V 1.0": {
        "1": "Na parte hidráulica, elétrica, manutenção em geral (torneiras, vaso sanitário, equipamentos, tomada, parede, piso, etc) estão funcionando de forma correta ou em perfeito estado de conservação?",
        "2": "Os uniformes estão completos e no padrão da Rede? (incluindo crachá e bandana)",
        "3": "Estão sendo utilizados utensílios e louças em bom estado de conservação?",
        "4": "Todos os produtos estão corretamente etiquetados e dentro da validade secundária?",
        "5": "Da perspectiva de segurança alimentar, o restaurante está PLENAMENTE LIMPO (o ambiente onde o alimento é manipulado está limpo, de maneira que utensílios e equipamentos estejam sem acúmulo de sujidade e que não ofereçam risco de contaminação aos alimentos). Marque apenas as não conformidades.",
        "6": "As mesas, cadeiras, escadas, vidros em geral estão em bom estado de conservação?",
        "7": "O certificado de potabilidade da água está dentro do prazo de validade? E a limpeza da caixa de água, caso exista?",
        "8": "Todos os colaboradores estão com os exames médicos em dia? Os exames se encontram na unidade? Atendente, caixa, gerente e encarregado: exame clínico. Colaboradores do setor de produção: Exame clinico, parasitológico (EPF), exame de urina (EAS), hemograma completo, exame micológico das unhas.",
        "9": "As instalações físicas como piso, parede e teto possuem revestimento liso, impermeável e lavável? Estes estão conservados, livre de rachaduras, trincas, goteiras, vazamentos, infiltrações, bolores, descascamentos, dentre outros, de maneira a não transmitir contaminantes aos alimentos?",
        "10": "Os ralos estão limpos? São sifonados e as grelhas possuem dispositivo que permitam seu fechamento?",
        "11": "As luminárias localizadas sobre a área de preparação dos alimentos são apropriadas e estar protegidas contra explosão e quedas acidentais?",
        "12": "Os equipamentos, móveis e utensílios são mantidos em adequado estado de conservação e são resistentes à corrosão e a repetidas operações de limpeza e desinfecção, não sendo de madeira?",
        "13": "A planilha de temperatura está sendo preenchida diariamente e de maneira correta?",
        "14": "A unidade possui Manual de Boas Práticas de Fabricação (MBPF)?",
        "15": "A análise microbiológica da unidade se encontra dentro do prazo de validade?  (Análise do alimento, utensílio e análise micológica da unhas dos colaboradores).",
        "16": "Qual faturamento médio da unidade COM e SEM serviço?",
        "17": "Qual o valor do CMV da loja?",
        "18": "Qual o valor do Estoque?",
        "19": "A unidade possui todos os insumos necessários para produção do cardápio e esses insumos são das marcas homologadas pela Rede?",
        "20": "A unidade está com os demais itens em conformidade com o exigido pela Rede e legislações vigentes? Exemplo: não possuir caixa de papelão na unidade, não utilizar pano de algodão, não possui objetos/utensílios de madeira.",
        "21": "As TVs estão passando conteúdo padrão Sushiloko?",
        "22": "Quais promoções vigentes na loja?",
        "23": "O controle de vetores e pragas urbanas é executado por empresa licenciada? A empresa fornece comprovante de execução?",
        "24": "Os letreiros não possuem nenhuma lâmpada queimada? Caso tenha, exite  lâmpadas queimadas no Menuboard?",
        "25": "Valor mensal de descontos na unidade?",
        "26": "O restaurante está bem iluminado, sem lâmpadas queimadas e de colorações diferentes?",
        "27": "O kit endomarketing, tabela de validade, tabelas de gramaturas, colinhas e kit atendimento estão presente e colados em locais adequados?",
        "28": "Tilápia cube, salmão cube, chicken cube, mini acarajé de salmão e tilápia, massas hot e ebitem, creme de prestígio, camarão pré empanado e misturas de farinhas estão conforme o  padrão da Rede?",
        "29": "Qual o valor de Sangria da unidade?",
        "30": "Há em estoque todos os materiais de apoio para atendimento (hashis com e sem liguinha, guardanapos ensacados personalizados, sacos krafts, embalagens prontas, cintas para temaki, shoyuzará e molhos prontos para viagem)?",
        "31": "TODOS os vegetais para yakissoba estão porcionados em quantidade suficiente, com gramatura correta e em boa aparência, mesmo estando apropriados para consumo?",
        "32": "Quais as promoçoes locais ativas na unidade? Estas estão sendo executadas da forma correta?",
        "33": "A unidade encontra-se livre de pragas urbanas (ratos, baratas, moscas, formigas e outros insetos)?",
        "34": "A organização das geladeiras e freezers estão sendo realizadas de forma adequada para a unidade? Ordem de produtos prontos, semi-prontos e crus estão sendo seguidas? Os gêneros alimentícios estão separadados por prateleiras ou barreira física (recipiente com tampa)? Observação: Nenhum produto cru pode estar junto com produto cozido ou gêneros alimentícios diferentes misturados em mesmo recipiente?",
        "35": "O descongelamento de proteínas está sendo feito de forma adequada e de acordo com o prazo de validade para descongelamento? (Permitido apenas dentro de refrigerador e separado conforme gêneros alimentícios).",
        "36": "Os óleos e gorduras utilizados são aquecidos a temperaturas não superiores a 180ºC, sendo substituídos imediatamente sempre que houver alteração evidente das características físico-químicas ou sensoriais, tais como aroma e sabor, e formação intensa de espuma e fumaça?",
        "37": "A unidade possui Programa de Controle Medico de Saúde Ocupacional (PCMSO) e Programa de Prevenção de Risco de Acidentes (PPRA) em dias? Caso não tenha, procure um serviço especializado em Engenharia de Segurança e Medicina do Trabalho (SMT).",
        "38": "Os materiais publicitários obrigatórios encontram-se presentes na loja (banner, display, mobile etc) e estão em locais adequados? (Material de atração externa deve ficar fora da loja, enquanto de conversão deve estar dentro da loja).",
        "39": "Os molhos padronizados exigidos pela franqueadora (Molho Teriaki, Molho Oriental e Calda Sushiloko) estão sendo utilizados em loja?",
        "40": "Os alimentos estão armazenados de forma organizada, em local limpo, separadamente de materiais de limpeza e descartáveis, colocados sobre paletes ou prateleiras e com espaçamento mínimo necessário para garantir adequada ventilação e limpeza do local?",
        "41": "Todos os produtos estão dentro da validade primária?",
        "42": "As temperaturas de equipamentos estão dentro do estipulado pela legislação vigente, exceto freezer de bebidas? Equipamentos refrigeradores de 0,0 ºC até 4,9ºC ; equipamentos congeladores de -12ºC até -22ºC e banho maria acima de 60ºC). Foi não conformidade na última avaliação realizada.",
        "43": "Valor dos cancelamentos de Tela?",
        "44": "Valor dos cancelamentos de Mesa?",
        "45": "Qualquer comunicação para clientes feito pela unidade, além da campanha vigente está sendo colocada de  maneira correta? A comunicação interna feita para colaboradores está sendo colocada no quadro de avisos ou de forma adequada e em perfeitas condições?",
        "46": "A unidade possui todos os equipamentos exigidos pela franqueadora (maquina de alga, estufa, termômetro, balança de  precisão) em quantidade adequada e funcionando perfeitamente?",
        "47": "Todos os itens de programação visual estão presentes (papel de parede, papel de balcão, sinalização nos vidros da loja, capacho, mentha fórmica, placas sinalizadoras na cozinha, estoque, escritório, banheiros, extintor, quadro de energia) ?",
        "48": "Todas as mesas possuem shoyo, chamador de garçom e display de mesa e/ou estes são colocados logo ao receber o cliente na unidade? O chamador de garçom / chamador de senha estão funcionando adequadamente?",
        "49": "O aspecto do sorvete está padrão, não estando petrificado e nem descongelado? É de marca homologada pela Rede?",
        "50": "Estão usando bandejas, utensílios e louças em perfeito estado de conservação e higiene (Atendimento)?",
        "51": "Os funcionários estão bem apresentáveis (TODOS sem NENHUM tipo de adorno, homens sem barba e/ou bigode, todos com unhas limpas e curtas, sendo permitido apenas maquiagem bem leve para área de atendimento e esmalte de cor clara).",
        "52": "Qual o valor do estoque?",
        "53": "Os letreiros não possuem nenhuma lâmpada queimada? Caso tenha, as lâmpdas do Menuboard não possuem nenhuma lâmpada queimada?",
        "54": "Estão usando bandejas, utensílios e louças em perfeito estado de conservação e higiene?"
    },
    "Visita técnica - Relatório aberto": {
        "1": "Quais foram os procedimentos realizados em loja?",
        "2": "Valor em branco"
    }
}